# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d92406688aeb5fa066e69eacd8a84c7bac83810e1e516aa58a7cbea750bee800230f3c1c7178ce8248015efe4858eb17a61372d97063fc87bb919ea9cda22637

test:
  secret_key_base: 5f1cefac133a3c4e4766331f7310a7002507b26a32e57f9e4072a02f6220a61356445b2b1d69e4104c83f51ba2293141d36169b6da372f3b8c4395c3f3222980

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
